
xcodeproj '/Users/javierrivarola/Documents/Tacuara Tech trabajos/APPS iOS/Calendario de Audiencias INDERT/Calendario de Audiencias INDERT.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.3'
pod 'HanekeSwift'
pod 'SwiftyJSON', '~> 2.2.0'